apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: debug-alert
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
    - name: debug.rules
      rules:
        - alert: AlwaysFiringDebug
          expr: vector(1)
          for: 30s
          labels:
            severity: critical
          annotations:
            summary: "Test Alert"
            description: "This alert always fires."