apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-sns-config
  namespace: monitoring
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: sns-notifications
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h

    receivers:
      - name: sns-notifications
        sns_configs:
          - topic_arn: arn:aws:sns:us-east-1:870017957268:eks-alerts
            sigv4:
              region: us-east-1
            send_resolved: true