apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: debug-alert
  namespace: monitoring
spec:
  groups:
    - name: debug.rules
      rules:
        - alert: AlwaysFiringDebug
          expr: vector(1)
          for: 30s