name: Dockerise Node App
on:
  push:
    paths:
      - 'App/**'
  pull_request:
    paths:
      - 'App/**'
  workflow_dispatch:
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

jobs:
  test:
    name: Test Node App
    runs-on: Ubuntu
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          
      - name: Run NPM test for frontend
        continue-on-error: true
        run: npm test
        working-directory: App/frontend
      
      - name: Run NPM test for backend
        continue-on-error: true
        run: npm test
        working-directory: App/backend

  container_scanning:
    name: Scanning Images using Trivy
    runs-on: ubuntu-24.04
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build an image from Frontend Dockerfile
        run: docker build -t ${{ secrets.ECR_REPOSITORY }}/frontend:${{ github.sha }} .
        working-directory: App/frontend
    
      - name: Build an image from Backend Dockerfile
        run: docker build -t ${{ secrets.ECR_REPOSITORY }}/backend:${{ github.sha }} .
        working-directory: App/backend

      - name: Run Trivy vulnerability scanner on Frontend image
        continue-on-error: true
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: '870017957268.dkr.ecr.us-east-1.amazonaws.com/nodeapp/frontend:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Run Trivy vulnerability scanner on Backend image
        continue-on-error: true
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: '870017957268.dkr.ecr.us-east-1.amazonaws.com/nodeapp/backend:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: container_scanning
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to AWS ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}
     
      - name: Build an image from Frontend Dockerfile
        run: docker build -t 870017957268.dkr.ecr.us-east-1.amazonaws.com/nodeapp/frontend:${{ github.sha }} .
        working-directory: App/frontend
    
      - name: Push Frontend Docker image
        run: docker push ${{ secrets.ECR_REPOSITORY }}/frontend:latest    

      - name: Build an image from Backend Dockerfile
        run: docker build -t 870017957268.dkr.ecr.us-east-1.amazonaws.com/nodeapp/backend:${{ github.sha }} .
        working-directory: App/backend

      - name: Push Frontend Docker image
        run: docker push ${{ secrets.ECR_REPOSITORY }}/backend:latest