name: "Infra Destroy"
on:
  workflow_dispatch:
    
jobs:
  destroy:
    runs-on: ubuntu-latest
    env:  
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
      TF_VAR_argocd_admin_password_hash: ${{ secrets.ARGO_CD_ADMIN_PASS }}
      TF_VAR_grafana_admin_password: ${{ secrets.GRAFANA_ADMIN_PASS }}  

    steps:
      - uses: actions/checkout@v4

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init - Platform
        run: terraform init
        working-directory: Platform/

      - name: Terraform Destroy - Platform
        run: terraform destroy -auto-approve
        working-directory: Platform/

      - name: Terraform Init - EKS
        run: terraform init
        working-directory: EKS/

      - name: Terraform Destroy - EKS
        run: terraform destroy -auto-approve
        working-directory: EKS/

      - name: Terraform Init - Infra 
        run: terraform init
        working-directory: Infra/

      - name: Terraform Destroy - Infra
        run: terraform destroy -auto-approve
        working-directory: Infra/