name: "Infra Setup"
on:
  push:
    paths:
      - 'Infra/**'
  pull_request:
    paths:
      - 'Infra/**'

jobs:
  terraform: 
    runs-on: ubuntu-latest

    env:  
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  

    steps:
      - uses: actions/checkout@v4
      
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
      
      - name: Terraform Init
        run: terraform init
        working-directory: Infra/
      
      - name: Terraform Plan
        run: terraform plan -out=tfplan 
        working-directory: Infra/

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: Infra/

  destroy:
    needs: terraform
    runs-on: ubuntu-latest
    environment:
        name: terraform-destroy
    env:  
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  

    steps:
      - uses: actions/checkout@v4

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init 
        run: terraform init

      - name: Terraform Destroy 
        run: terraform destroy -auto-approve