name: "Infra Setup"
on:
  workflow_dispatch:
  push:
    paths:
      - 'Infra/**'
  pull_request:
    paths:
      - 'Infra/**'

jobs:
  terraform-infra: 
    runs-on: ubuntu-latest

    env:  
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  

    steps:
      - uses: actions/checkout@v4
      
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
      
      - name: Terraform Init
        run: terraform init
        working-directory: Infra/
      
      - name: Terraform Plan
        run: terraform plan -out=tfplan 
        working-directory: Infra/

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: Infra/

  terraform-platform: 
    needs: terraform-infra
    runs-on: ubuntu-latest

    env:  
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  

    steps:
      - uses: actions/checkout@v4
      
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
      
      - name: Terraform Init
        run: terraform init
        working-directory: Platform/
      
      - name: Terraform Plan
        run: terraform plan -out=tfplan 
        working-directory: Platform/

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: Platform/